import Head from "next/head";
import Layout from "@/components/Layout/Layout";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Foodieland | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        Blog
      </Layout>
    </>
  );
}
