import BlogBanner from '@/components/Blog/Banner/BlogBanner'
import BlogMain from '@/components/Blog/BlogMain/BlogMain'
import Form from '@/components/common/Form/Form'
import Layout from '@/components/common/Layout/Layout'
import Map from '@/components/common/Map/Map'
import Head from 'next/head'
import React from 'react'



export default function blog(){
  return (
    <>
    
      <Head>
        <title>Highlands | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BlogBanner />
        <BlogMain />
        <Map />
      </Layout>
    </>
  );
}