import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/common/Layout/Layout";
import MenuPopup from "@/components/common/MenuPopup/MenuPopup";
import Blueprint from "@/components/Home/Blueprint/Blueprint";
import HomeBanner from "@/components/Home/HomeBanner/HomeBanner";
import HomeVideo from "@/components/Home/HomeVideo/HomeVideo";
import HomeSlider from "@/components/Home/HomeSlider/HomeSlider";
import HousePlan from "@/components/Home/HousePlan/HousePlan";
import Glance from "@/components/Home/Glance/Glance";
import Planet from "@/components/Home/Planet/Planet";
import Faq from "@/components/Home/Faq/Faq";
import Form from "@/components/common/Form/Form";
import Map from "@/components/common/Map/Map";
import Explore from "@/components/Home/Explore/Explore";



export default function Home() {
  return (
    <>
      <Head>
        <title>Highlands | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeBanner />
         <HomeVideo/>  
        <HomeSlider/>
        <HousePlan/>      
        <Explore/>    
         <Blueprint/>
        <Glance/>
        <Planet /> 
        <Faq/>
        <Map/>
      </Layout>
    </>
  );
}
